"""empty message

Revision ID: 190a068a4ac9
Revises: 169f9104ac38
Create Date: 2025-05-22 10:39:24.189985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190a068a4ac9'
down_revision = '169f9104ac38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
