"""empty message

Revision ID: 5c72073e5043
Revises: f6074e3d3ea1
Create Date: 2025-06-05 11:30:13.663130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c72073e5043'
down_revision = 'f6074e3d3ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('answer_model_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('answer_model_question_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_author_id_fkey', 'user', ['author_id'], ['id'])

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answer_model_question_id_fkey', 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key('answer_model_author_id_fkey', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
