"""empty message

Revision ID: 77faf40ed69a
Revises: d6a086e2f297
Create Date: 2025-06-04 15:23:59.751467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77faf40ed69a'
down_revision = 'd6a086e2f297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
